# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update_data"
  update_data:
    name: Update Brazil Covid19 data
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install python dependencies
      run: pip3 install pandas

    # Runs a python script that fetchs the data
    - name: Fetch official data
      run: python3 fetch_official_data.py

    # Test if file is being updated
    - name: Test file generation
      run: cat HIST_PAINEL_COVIDBR.csv
